#!/bin/sh

# scrippies/configure-npm

set -euvx

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly whatami="$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

log() { echo "${whatami}[$$]: $@" >&2; }
error() { log "ERROR: $@"; }
warning() { log "WARNING: $@"; }
info() { log "INFO: $@"; }

die() {
    error "$@"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}"
    return "${status}"
}

usage() {
    cat <<EOF
Usage: $0 [OPTION]... [DISTRIBUTION]
Configure npm to not suck. Well, try, at any rate.

Options:
    -h    print usage and exit

Examples:

    \$ $0 -h

    \$ $0

EOF
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

while getopts ":hf:" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((${OPTIND} - 1))"

if ! [ -x /usr/bin/npm ]; then
    die "missing executable: /usr/bin/npm"
fi

tee >/usr/local/bin/npm <<'EOF'
#!/bin/sh
set -euvx
flock /usr/local/bin/npm -c "/usr/bin/npm $*"
EOF
chmod +x /usr/local/bin/npm

if ! [ "/usr/local/bin/npm" = "$(command -v npm)" ]; then
    die "missing executable: /usr/local/bin/npm"
fi

npm --global config set progress=false

if getent hosts verdaccio.realtime.cxm; then
    npm --global config set registry http://verdaccio.realtime.cxm:4873/
    tee -a /etc/hosts <<'EOF'
0.0.0.0 registry.npmjs.org
EOF
fi

exit "$?"
