#!/bin/sh

# scrippies/configure-npm

set -eu

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly whatami="$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

log() { echo "${whatami}[$$]: $@" >&2; }
error() { log "ERROR: $@"; }
warning() { log "WARNING: $@"; }
info() { log "INFO: $@"; }

die() {
    error "$@"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}"
    return "${status}"
}

usage() {
    cat <<EOF
Usage: $0 [OPTION]... [DISTRIBUTION]
Configure npm to not suck. Well, try, at any rate.

Options:
    -h    print usage and exit

Examples:

    \$ $0 -h

    \$ $0

EOF
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

while getopts ":hf:" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((${OPTIND} - 1))"

if ! cmd_npm="$(command -v npm)"; then
    die "missing command: npm"
fi
export cmd_npm

if dpkg-divert --list "${cmd_npm}.distrib" | grep -q "${cmd_npm}.distrib"; then
    warning "already diverted: ${cmd_npm}"
else
    info "$(dpkg-divert --local --rename "${cmd_npm}")"
    envsubst '${cmd_npm}' >"${cmd_npm}" <<'EOF'
#!/bin/sh
set -eu
cleanup() {
    local status="$?"
    rm -rf "${NPM_CONFIG_CACHE}" || true
    return "${status}"
}
trap cleanup EXIT
export NPM_CONFIG_CACHE="$(mktemp -dt npm_config_cache.XXXXXX)"
flock ${cmd_npm} -c "${cmd_npm}.distrib --cache ${NPM_CONFIG_CACHE} $*"
EOF
    chmod +x "${cmd_npm}"
    info "$(file "${cmd_npm}")"
fi

if getent hosts verdaccio.realtime.cxm >/dev/null 2>&1; then
    npm --global config set registry http://verdaccio.realtime.cxm:4873/
else
    npm --global config delete registry
fi

npm --global config list

exit "$?"
