#!/bin/sh

# scrippies/configure-apt

set -eu

readonly this="$(readlink -f "$0")"
readonly whatami="$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

log() { echo "${whatami}[$$]: $*" >&2; }
error() { log "ERROR: $*"; }
warning() { log "WARNING: $*"; }
info() { log "INFO: $*"; }

die() {
    error "$*"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}"
    return "${status}"
}

usage() {
    cat <<EOF

Usage: $0 [OPTION]... [DISTRIBUTION]
Configure apt to use additional repositories.

Options:

    -h            print usage and exit
    -f NETWORK    force NETWORK={private,public} (default is to discover)

Notes:

    * If not given, DISTRIBUTION discovery is attempted via \`lsb_release -sc\`
      or, failing that, the \`/etc/os-release\` definition for
      \`UBUNTU_CODENAME\`.

Examples:

    \$ $0

    \$ $0 -f private

    \$ $0 -f public

    \$ $0 trusty

    \$ $0 xenial

    \$ $0 bionic

EOF
}

# 3.282 Portable Filename Character Set
# https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282
filenamify() {
    printf '%s' "$*" | tr -sc '[:alnum:]._-' '_'
}

apt_config_path() {
    cut -d= -f2 | xargs -n1 | paste -sd/ | xargs readlink -f
}

etc_apt_sources_list() {
    apt-config shell _ Dir _ Dir::Etc _ Dir::Etc::sourcelist | apt_config_path
}

etc_apt_sources_list_d() {
    apt-config shell _ Dir _ Dir::Etc _ Dir::Etc::sourceparts | apt_config_path
}

etc_apt_apt_conf_d() {
    apt-config shell _ Dir _ Dir::Etc _ Dir::Etc::parts | apt_config_path
}

etc_apt_preferences_d() {
    apt-config shell _ Dir _ Dir::Etc _ Dir::Etc::preferencesparts | apt_config_path
}

etc_apt_trusted_gpg_d() {
    apt-config shell _ Dir _ Dir::Etc _ Dir::Etc::trustedparts | apt_config_path
}

detect_distribution() {
    # shellcheck disable=SC2039
    local result=""
    if command -v lsb_release >/dev/null 2>&1; then
        if result="$(lsb_release --short --codename)"; then
            echo "${result}"
            return 0
        else
            warning "FAILURE: lsb_release --short --codename"
        fi
    else
        warning "missing command: lsb_release"
    fi
    if [ -f /etc/os-release ]; then
        # shellcheck disable=1091
        if result="$(
            . /etc/os-release
            echo "${UBUNTU_CODENAME:-}"
        )"; then
            echo "${result}"
            return 0
        else
            warning "/etc/os-release: undefined UBUNTU_CODENAME"
        fi
    else
        warning "missing file: /etc/os-release"
    fi
    return 1
}

vet_force_network() {
    case "$1" in
        private)
            echo "$1"
            return 0
            ;;
        public)
            echo "$1"
            return 0
            ;;
        *)
            error "bad force_network: $1"
            return 1
            ;;
    esac
}

# Take some things that describe an apt repository. Write a generated apt
# sources list file that enables the referenced repository.
#
# $1 : repo_uri  ; https://wiki.debian.org/SourcesList#Repository_URL
# $2 : atyp_list ; https://wiki.debian.org/SourcesList#Archive_type
# $3 : dist_list ; https://wiki.debian.org/SourcesList#Distribution
# $4 : comp_list ; https://wiki.debian.org/SourcesList#Component
setup_apt_list() {
    # shellcheck disable=SC2039
    local repo_uri="$1"
    # shellcheck disable=SC2039
    local atyp_list="$2"
    # shellcheck disable=SC2039
    local dist_list="$3"
    # shellcheck disable=SC2039
    local comp_list="$4"

    # list file is named for the uri it references
    # shellcheck disable=SC2039
    local apt_list_file=""
    apt_list_file="$(etc_apt_sources_list_d)/$(filenamify "${repo_uri}").list"
    info "installing: ${apt_list_file}"
    if [ -f "${apt_list_file}" ]; then
        warning "file exists: ${apt_list_file}"
        warning "$(mv -v "${apt_list_file}" "${apt_list_file}.save")"
    fi
    # write header
    cat >"${apt_list_file}" <<EOF
# ${apt_list_file}
#
# This is a generated apt sources list file.
#
# https://wiki.debian.org/SourcesList
#
# generator : ${this}
# user      : $(id)
# uname     : $(uname -a)
# date      : $(date -u +"%Y-%m-%dT%H:%M:%SZ")

EOF
    # write body
    # Make sure atyp and dist are padded to the longest member
    # shellcheck disable=SC2039
    local atyp_width=""
    atyp_width="$(wc -L <"${atyp_list}")"
    # shellcheck disable=SC2039
    local dist_width=""
    dist_width="$(wc -L <"${dist_list}")"
    while read -r atyp; do
        while read -r dist; do
            printf "%-${atyp_width}s %s %-${dist_width}s %s\n" \
                "${atyp}" \
                "${repo_uri}" \
                "${dist}" \
                "$(paste -sd' ' <"${comp_list}")"
        done <"${dist_list}"
    done <"${atyp_list}" >>"${apt_list_file}"
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

while getopts ":hf:" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        f)
            if ! force_network="$(vet_force_network "${OPTARG}")"; then
                die "FAILURE: vet_force_network ${OPTARG}"
            fi
            readonly force_network="${force_network}"
            readonly use_network="${force_network}"
            ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((OPTIND - 1))"

case "$#" in
    0)
        warning "missing distribution; will attempt to discover"
        if ! distribution="$(detect_distribution)"; then
            die "FAILURE: detect_distribution"
        fi
        readonly distribution="${distribution}"
        info "detected distribution: ${distribution}"
        ;;
    1)
        readonly distribution="$1"
        ;;
    *)
        die "bad args"
        ;;
esac

if [ -n "${use_network:-}" ]; then
    info "use_network: ${use_network}"
else
    # https://serverfault.com/questions/13780/how-can-i-determine-if-a-machine-is-online-without-using-ping/923193#923193
    # https://unix.stackexchange.com/questions/148985/how-to-get-a-response-from-any-url/148989#148989
    if getent hosts apt.realtime.cxm >/dev/null 2>&1; then
        readonly use_network="private"
    else
        readonly use_network="public"
    fi
    warning "discovered use_network: ${use_network}"
fi

################################################################################

#######################################
# ################################### #
# # LAUNCHPAD PPA REALTIME-ROBOTICS # #
# ################################### #
#######################################

# pub   4096R/8A68278A 2020-03-16
# uid                  Launchpad PPA for realtime-robotics
cat >"$(etc_apt_trusted_gpg_d)/0xae0f78ce556b80ab48ce556f208dac2d8a68278a.asc" <<'EOF'
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBF5vsKcBEACw/lMOWu4aQBG2155Tqji9x7S7QqOIoXdzHLu1J7uih3DHweoS
WniSjaL3HZGTjyte/h2JZLRsEeEOLeCd8UfYatAmZowlMfiF5NkbZx2bvLrepGfc
/IY9stEA8lCihlowaWSmbZQII4P12SFUJTpSOoScc22NVebgZ2f/X85NgyDOBxyn
j1QA7N1LMVJntWFLYz6ARlkEtLwyzX+v7Z/5SU9H5frRW0WLs8qpRwvtS3ysNOO+
r4/vUM79okQCj7pm4tUMNHG2at5fZ5OilyYzGb9+3aRXVpuij9jDUq04UHSVeazf
UHMOgOVtOp/sWfBD0GNRclsqdvkV3tPc5j+nL+RlXD2Ou6SOT5RgosmTB/4J53SX
30A110r3tP4Ng1HCzLweyX8qUxZ2jGp0iy/p2WYqNHXw0Rjx3aUpNU+23zSQCmi9
um4/Vr1KsUgOHKgK9hi1xBGYOO5g8XvKwZlJA5t7c+3lLNxm7fKO4rxYbDcZqbXR
sw/8EDcQUAFzxCFdCwoTrll7E7afQtOqGSlrh3XtfCXegsiZ3t9vjXaZ7YeC4S09
fcLUnQxuJcY6PKxFfomPzbzwIhrYIwvOcBw92RVOFA8D+IWBQ1KS8cRvultFwDUW
+P8R4blkStZVdjQ2g5G2y/VpMvoaflrwGxo3Yingc+nD4qysOCxQkyYFlwARAQAB
tCNMYXVuY2hwYWQgUFBBIGZvciByZWFsdGltZS1yb2JvdGljc4kCOAQTAQIAIgUC
Xm+wpwIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQII2sLYpoJ4oe1BAA
ktoNpKxfriOJzhwAFTsF2XFJ0rM6WjYtOVAoIxJXG5c8jOcY5WtZ14/hx4DrK3nf
z/WMDN8xaCzBOeLZ3V12IUKJ2LHZSmkxqfcd2mlzrJ3kYDnl7q6UEjCwk8ly4JG1
5L5A8E5rnEU/Q26jy+X3DosKFuTPk61H0xOfBdkeQOckXcpphKi468d9qXhoQcSB
JgDxuFLU34JKJIj8HmtWGTjGtQJ/66nyf0FBWaB0r6Q+Si5mr26dy7TEWmu6OzXO
rtrxdM0kiI1NPCiq/l9kuTzgtr2CK/VxW17Vc6tGAFOvw7up75ZbbAnqnMSNrqdO
cmM2ZlSmT5CIzwwYuVWYdCX+m2GSiqOjZq9Ob1AKKxp/SEyoClR4tqKJmomd8kSG
rJneB0GeDjWTIZ5tMhgFdGpC/uDOcmxR3u6RytBV4QDp06Ds6mdLyLQavyI9xTRT
k7huI3vBzihDU03NdIwP7B5XpLLuvsNGFCcWbMf5jXa0LUsz87K62isf/k+kj+s7
d7KoqI4jNU1ezdBDF9RLgH/95vtxPxHPwXDOo6+tBhtfCFSdunEJI5EVrJwvj/B5
ozM0yFMCDZQqpZ/CAxH9CjxIPM21vennMKuwikGOkDj2pjKmHpWGWwIRuGUi30cc
+Lsb1DP4pkVCeaMupLVMxPzStktUUea6A23Exu8WNq+ZAg0EXm+wpwEQALD+Uw5a
7hpAEbbXnlOqOL3HtLtCo4ihd3Mcu7Unu6KHcMfB6hJaeJKNovcdkZOPK17+HYlk
tGwR4Q4t4J3xR9hq0CZmjCUx+IXk2RtnHZu8ut6kZ9z8hj2y0QDyUKKGWjBpZKZt
lAgjg/XZIVQlOlI6hJxzbY1V5uBnZ/9fzk2DIM4HHKePVADs3UsxUme1YUtjPoBG
WQS0vDLNf6/tn/lJT0fl+tFbRYuzyqlHC+1LfKw0476vj+9Qzv2iRAKPumbi1Qw0
cbZq3l9nk6KXJjMZv37dpFdWm6KP2MNSrThQdJV5rN9Qcw6A5W06n+xZ8EPQY1Fy
Wyp2+RXe09zmP6cv5GVcPY67pI5PlGCiyZMH/gnndJffQDXXSve0/g2DUcLMvB7J
fypTFnaManSLL+nZZio0dfDRGPHdpSk1T7bfNJAKaL26bj9WvUqxSA4cqAr2GLXE
EZg47mDxe8rBmUkDm3tz7eUs3Gbt8o7ivFhsNxmptdGzD/wQNxBQAXPEIV0LChOu
WXsTtp9C06oZKWuHde18Jd6CyJne32+Ndpnth4LhLT19wtSdDG4lxjo8rEV+iY/N
vPAiGtgjC85wHD3ZFU4UDwP4hYFDUpLxxG+6W0XANRb4/xHhuWRK1lV2NDaDkbbL
9Wky+hp+WvAbGjdiKeBz6cPirKw4LFCTJgWXABEBAAG0I0xhdW5jaHBhZCBQUEEg
Zm9yIHJlYWx0aW1lLXJvYm90aWNziQI4BBMBAgAiBQJeb7CnAhsDBgsJCAcDAgYV
CAIJCgsEFgIDAQIeAQIXgAAKCRAgjawtimgnih7UEACS2g2krF+uI4nOHAAVOwXZ
cUnSszpaNi05UCgjElcblzyM5xjla1nXj+HHgOsred/P9YwM3zFoLME54tndXXYh
QonYsdlKaTGp9x3aaXOsneRgOeXurpQSMLCTyXLgkbXkvkDwTmucRT9DbqPL5fcO
iwoW5M+TrUfTE58F2R5A5yRdymmEqLjrx32peGhBxIEmAPG4UtTfgkokiPwea1YZ
OMa1An/rqfJ/QUFZoHSvpD5KLmavbp3LtMRaa7o7Nc6u2vF0zSSIjU08KKr+X2S5
POC2vYIr9XFbXtVzq0YAU6/Du6nvlltsCeqcxI2up05yYzZmVKZPkIjPDBi5VZh0
Jf6bYZKKo6Nmr05vUAorGn9ITKgKVHi2oomaiZ3yRIasmd4HQZ4ONZMhnm0yGAV0
akL+4M5ybFHe7pHK0FXhAOnToOzqZ0vItBq/Ij3FNFOTuG4je8HOKENTTc10jA/s
Hleksu6+w0YUJxZsx/mNdrQtSzPzsrraKx/+T6SP6zt3sqiojiM1TV7N0EMX1EuA
f/3m+3E/Ec/BcM6jr60GG18IVJ26cQkjkRWsnC+P8HmjMzTIUwINlCqln8IDEf0K
PEg8zbW96ecwq7CKQY6QOPamMqYelYZbAhG4ZSLfRxz4uxvUM/imRUJ5oy6ktUzE
/NK2S1RR5roDbcTG7xY2rw==
=/ymJ
-----END PGP PUBLIC KEY BLOCK-----
EOF

################################################################################

#######################################
# LAUNCHPAD PPA REALTIME-ROBOTICS ROS #
#######################################

if [ "private" = "${use_network:-public}" ]; then
    readonly rtr_ros_repo_uri="http://apt.realtime.cxm/apt/realtime-robotics/ros/${distribution}"
else
    readonly rtr_ros_repo_uri="http://ppa.launchpad.net/realtime-robotics/ros/ubuntu"
fi
readonly rtr_ros_atyp_list="$(mktemp -t rtr_ros_atyp_list.XXXXXX)"
cat >"${rtr_ros_atyp_list}" <<'EOF'
deb
deb-src
EOF
readonly rtr_ros_dist_list="$(mktemp -t rtr_ros_dist_list.XXXXXX)"
cat >"${rtr_ros_dist_list}" <<EOF
${distribution}
EOF
readonly rtr_ros_comp_list="$(mktemp -t rtr_ros_comp_list.XXXXXX)"
cat >"${rtr_ros_comp_list}" <<'EOF'
main
EOF
case "${distribution}" in
    xenial | bionic)
        setup_apt_list \
            "${rtr_ros_repo_uri}" \
            "${rtr_ros_atyp_list}" \
            "${rtr_ros_dist_list}" \
            "${rtr_ros_comp_list}"
        ;;
    *)
        warning "missing ${distribution}: ${rtr_ros_repo_uri}"
        ;;
esac

################################################################################

###########################################
# LAUNCHPAD PPA REALTIME-ROBOTICS FREECAD #
###########################################

if [ "private" = "${use_network:-public}" ]; then
    readonly rtr_freecad_repo_uri="http://apt.realtime.cxm/apt/realtime-robotics/freecad/${distribution}"
else
    readonly rtr_freecad_repo_uri="http://ppa.launchpad.net/realtime-robotics/freecad/ubuntu"
fi
readonly rtr_freecad_atyp_list="$(mktemp -t rtr_freecad_atyp_list.XXXXXX)"
cat >"${rtr_freecad_atyp_list}" <<'EOF'
deb
deb-src
EOF
readonly rtr_freecad_dist_list="$(mktemp -t rtr_freecad_dist_list.XXXXXX)"
cat >"${rtr_freecad_dist_list}" <<EOF
${distribution}
EOF
readonly rtr_freecad_comp_list="$(mktemp -t rtr_freecad_comp_list.XXXXXX)"
cat >"${rtr_freecad_comp_list}" <<'EOF'
main
EOF
case "${distribution}" in
    xenial | bionic)
        setup_apt_list \
            "${rtr_freecad_repo_uri}" \
            "${rtr_freecad_atyp_list}" \
            "${rtr_freecad_dist_list}" \
            "${rtr_freecad_comp_list}"
        ;;
    *)
        warning "missing ${distribution}: ${rtr_ros_repo_uri}"
        ;;
esac

################################################################################

########
# NODE #
########

# pub   4096R/68576280 2014-06-13
# uid                  NodeSource <gpg@nodesource.com>
# sub   4096R/AA01DA2C 2014-06-13
cat >"$(etc_apt_trusted_gpg_d)/0x9fd3b784bc1c6fc31a8a0a1c1655a0ab68576280.asc" <<'EOF'
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1
Comment: GPGTools - https://gpgtools.org

mQINBFObJLYBEADkFW8HMjsoYRJQ4nCYC/6Eh0yLWHWfCh+/9ZSIj4w/pOe2V6V+
W6DHY3kK3a+2bxrax9EqKe7uxkSKf95gfns+I9+R+RJfRpb1qvljURr54y35IZgs
fMG22Np+TmM2RLgdFCZa18h0+RbH9i0b+ZrB9XPZmLb/h9ou7SowGqQ3wwOtT3Vy
qmif0A2GCcjFTqWW6TXaY8eZJ9BCEqW3k/0Cjw7K/mSy/utxYiUIvZNKgaG/P8U7
89QyvxeRxAf93YFAVzMXhoKxu12IuH4VnSwAfb8gQyxKRyiGOUwk0YoBPpqRnMmD
Dl7SdmY3oQHEJzBelTMjTM8AjbB9mWoPBX5G8t4u47/FZ6PgdfmRg9hsKXhkLJc7
C1btblOHNgDx19fzASWX+xOjZiKpP6MkEEzq1bilUFul6RDtxkTWsTa5TGixgCB/
G2fK8I9JL/yQhDc6OGY9mjPOxMb5PgUlT8ox3v8wt25erWj9z30QoEBwfSg4tzLc
Jq6N/iepQemNfo6Is+TG+JzI6vhXjlsBm/Xmz0ZiFPPObAH/vGCY5I6886vXQ7ft
qWHYHT8jz/R4tigMGC+tvZ/kcmYBsLCCI5uSEP6JJRQQhHrCvOX0UaytItfsQfLm
EYRd2F72o1yGh3yvWWfDIBXRmaBuIGXGpajC0JyBGSOWb9UxMNZY/2LJEwARAQAB
tB9Ob2RlU291cmNlIDxncGdAbm9kZXNvdXJjZS5jb20+iQI4BBMBAgAiBQJTmyS2
AhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRAWVaCraFdigHTmD/9OKhUy
jJ+h8gMRg6ri5EQxOExccSRU0i7UHktecSs0DVC4lZG9AOzBe+Q36cym5Z1di6JQ
kHl69q3zBdV3KTW+H1pdmnZlebYGz8paG9iQ/wS9gpnSeEyx0Enyi167Bzm0O4A1
GK0prkLnz/yROHHEfHjsTgMvFwAnf9uaxwWgE1d1RitIWgJpAnp1DZ5O0uVlsPPm
XAhuBJ32mU8S5BezPTuJJICwBlLYECGb1Y65Cil4OALU7T7sbUqfLCuaRKxuPtcU
VnJ6/qiyPygvKZWhV6Od0Yxlyed1kftMJyYoL8kPHfeHJ+vIyt0s7cropfiwXoka
1iJB5nKyt/eqMnPQ9aRpqkm9ABS/r7AauMA/9RALudQRHBdWIzfIg0Mlqb52yyTI
IgQJHNGNX1T3z1XgZhI+Vi8SLFFSh8x9FeUZC6YJu0VXXj5iz+eZmk/nYjUt4Mtc
pVsVYIB7oIDIbImODm8ggsgrIzqxOzQVP1zsCGek5U6QFc9GYrQ+Wv3/fG8hfkDn
xXLww0OGaEQxfodm8cLFZ5b8JaG3+Yxfe7JkNclwvRimvlAjqIiW5OK0vvfHco+Y
gANhQrlMnTx//IdZssaxvYytSHpPZTYw+qPEjbBJOLpoLrz8ZafN1uekpAqQjffI
AOqW9SdIzq/kSHgl0bzWbPJPw86XzzftewjKNbkCDQRTmyS2ARAAxSSdQi+WpPQZ
fOflkx9sYJa0cWzLl2w++FQnZ1Pn5F09D/kPMNh4qOsyvXWlekaV/SseDZtVziHJ
Km6V8TBG3flmFlC3DWQfNNFwn5+pWSB8WHG4bTA5RyYEEYfpbekMtdoWW/Ro8Kmh
41nuxZDSuBJhDeFIp0ccnN2Lp1o6XfIeDYPegyEPSSZqrudfqLrSZhStDlJgXjea
JjW6UP6txPtYaaila9/Hn6vF87AQ5bR2dEWB/xRJzgNwRiax7KSU0xca6xAuf+TD
xCjZ5pp2JwdCjquXLTmUnbIZ9LGV54UZ/MeiG8yVu6pxbiGnXo4Ekbk6xgi1ewLi
vGmz4QRfVklV0dba3Zj0fRozfZ22qUHxCfDM7ad0eBXMFmHiN8hg3IUHTO+UdlX/
aH3gADFAvSVDv0v8t6dGc6XE9Dr7mGEFnQMHO4zhM1HaS2Nh0TiL2tFLttLbfG5o
QlxCfXX9/nasj3K9qnlEg9G3+4T7lpdPmZRRe1O8cHCI5imVg6cLIiBLPO16e0fK
yHIgYswLdrJFfaHNYM/SWJxHpX795zn+iCwyvZSlLfH9mlegOeVmj9cyhN/VOmS3
QRhlYXoA2z7WZTNoC6iAIlyIpMTcZr+ntaGVtFOLS6fwdBqDXjmSQu66mDKwU5Ek
fNlbyrpzZMyFCDWEYo4AIR/18aGZBYUAEQEAAYkCHwQYAQIACQUCU5sktgIbDAAK
CRAWVaCraFdigIPQEACcYh8rR19wMZZ/hgYv5so6Y1HcJNARuzmffQKozS/rxqec
0xM3wceL1AIMuGhlXFeGd0wRv/RVzeZjnTGwhN1DnCDy1I66hUTgehONsfVanuP1
PZKoL38EAxsMzdYgkYH6T9a4wJH/IPt+uuFTFFy3o8TKMvKaJk98+Jsp2X/QuNxh
qpcIGaVbtQ1bn7m+k5Qe/fz+bFuUeXPivafLLlGc6KbdgMvSW9EVMO7yBy/2JE15
ZJgl7lXKLQ31VQPAHT3an5IV2C/ie12eEqZWlnCiHV/wT+zhOkSpWdrheWfBT+ac
hR4jDH80AS3F8jo3byQATJb3RoCYUCVc3u1ouhNZa5yLgYZ/iZkpk5gKjxHPudFb
DdWjbGflN9k17VCf4Z9yAb9QMqHzHwIGXrb7ryFcuROMCLLVUp07PrTrRxnO9A/4
xxECi0l/BzNxeU1gK88hEaNjIfviPR/h6Gq6KOcNKZ8rVFdwFpjbvwHMQBWhrqfu
G3KaePvbnObKHXpfIKoAM7X2qfO+IFnLGTPyhFTcrl6vZBTMZTfZiC1XDQLuGUnd
sckuXINIU3DFWzZGr0QrqkuE/jyr7FXeUJj9B7cLo+s/TXo+RaVfi3kOc9BoxIvy
/qiNGs/TKy2/Ujqp/affmIMoMXSozKmga81JSwkADO1JMgUy6dApXz9kP4EE3g==
=CLGF
-----END PGP PUBLIC KEY BLOCK-----
EOF

#############
# node_10.x #
#############
if [ "private" = "${use_network:-public}" ]; then
    readonly node_10_x_repo_uri="http://apt.realtime.cxm/apt/node_10.x/${distribution}"
else
    readonly node_10_x_repo_uri="http://deb.nodesource.com/node_10.x"
fi
readonly node_10_x_atyp_list="$(mktemp -t node_10_x_atyp_list.XXXXXX)"
cat >"${node_10_x_atyp_list}" <<'EOF'
deb
deb-src
EOF
readonly node_10_x_dist_list="$(mktemp -t node_10_x_dist_list.XXXXXX)"
cat >"${node_10_x_dist_list}" <<EOF
${distribution}
EOF
readonly node_10_x_comp_list="$(mktemp -t node_10_x_comp_list.XXXXXX)"
cat >"${node_10_x_comp_list}" <<'EOF'
main
EOF
setup_apt_list \
    "${node_10_x_repo_uri}" \
    "${node_10_x_atyp_list}" \
    "${node_10_x_dist_list}" \
    "${node_10_x_comp_list}"

#############
# node_14.x #
#############
if [ "private" = "${use_network:-public}" ]; then
    readonly node_14_x_repo_uri="http://apt.realtime.cxm/apt/node_14.x/${distribution}"
else
    readonly node_14_x_repo_uri="http://deb.nodesource.com/node_14.x"
fi
readonly node_14_x_atyp_list="$(mktemp -t node_14_x_atyp_list.XXXXXX)"
cat >"${node_14_x_atyp_list}" <<'EOF'
deb
deb-src
EOF
readonly node_14_x_dist_list="$(mktemp -t node_14_x_dist_list.XXXXXX)"
cat >"${node_14_x_dist_list}" <<EOF
${distribution}
EOF
readonly node_14_x_comp_list="$(mktemp -t node_14_x_comp_list.XXXXXX)"
cat >"${node_14_x_comp_list}" <<'EOF'
main
EOF
setup_apt_list \
    "${node_14_x_repo_uri}" \
    "${node_14_x_atyp_list}" \
    "${node_14_x_dist_list}" \
    "${node_14_x_comp_list}"

################################################################################

#############
# REALSENSE #
#############

# pub   rsa2048 2018-01-09 [SC] [expires: 2028-01-08]
# uid           [ unknown] "CN = Intel(R) Intel(R) Realsense", O=Intel Corporation
cat >"$(etc_apt_trusted_gpg_d)/0xf6e65ac044f831ac80a06380c8b3a55a6f3efcde.asc" <<'EOF'
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBFpUqDEBCADuIoVeNfgr3owUxn0keHq9OPak+Phxk4ye/paDZ5JZ6D407GXt
QI0Ct6TVj2J9tWkcsK+G4DDxOQDPLIMf+mgjJYX0jwt6ruminSIhhp5fvh3Ol33e
X/2P01Iul/GhVlpg6MspnIiJOnv0okYNbOzSLdgxpmTk6dyxP49pHbLdzI7JugsS
tJljQgBeBP6pNlzBVTDvEvP2cXnqTVFxm2skiw9hyN2o2CXjGhGOz6Z5L6iOf/ee
8beYHomkEaaoNXc3Z+V5KzSg4uM1uYzqecxQ1InhrsYfb0ETjvAeJiNp1y+sSm+O
CDJWNxJq8tNSFrwvKPZ+e6cvv15yN6hChkkRABEBAAG0NyJDTiA9IEludGVsKFIp
IEludGVsKFIpIFJlYWxzZW5zZSIsIE89SW50ZWwgQ29ycG9yYXRpb26JAT4EEwEI
ACgFAlpUqDECGwMFCRLNVIAGCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJEMiz
pVpvPvzeGIAIAJiwFHVL/iqnDRVfzcI/Nm8gtoMDV2hU6QGcNkbwZn5JpoIyGGPh
zR01rWYX6hvt9BzzZljW7MF6LPnfi0IXzZ8ml/wFx0GwF9u0acCkxCZr4aIReO4W
t0Pe8u6uAIyhNdn9a4yacxFPdeU2W2w1xDTRUidiDO4V9vCllK4VGGHoBLi9ua6C
qIZrdnRvX3ire6WybLz33JyDbEK9SlKqs8kwyz4uq9a0sry79oTQiK4jAgLxKGq/
JA5ixemTnVrVIa+CZgUHqMW0SrgZeJDVMh7x2ZPGilSxmPDMNniEd5mxrFetFrzy
quh0EmUG2XwVM89VNH4Y45USyqal4RhISMw=
=IokU
-----END PGP PUBLIC KEY BLOCK-----
EOF
if [ "private" = "${use_network:-public}" ]; then
    readonly realsense_repo_uri="http://apt.realtime.cxm/apt/realsense/${distribution}"
else
    readonly realsense_repo_uri="http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo"
fi
readonly realsense_atyp_list="$(mktemp -t realsense_atyp_list.XXXXXX)"
cat >"${realsense_atyp_list}" <<'EOF'
deb
EOF
readonly realsense_dist_list="$(mktemp -t realsense_dist_list.XXXXXX)"
cat >"${realsense_dist_list}" <<EOF
${distribution}
EOF
readonly realsense_comp_list="$(mktemp -t realsense_comp_list.XXXXXX)"
cat >"${realsense_comp_list}" <<'EOF'
main
EOF
setup_apt_list \
    "${realsense_repo_uri}" \
    "${realsense_atyp_list}" \
    "${realsense_dist_list}" \
    "${realsense_comp_list}"

################################################################################

#######
# ROS #
#######

# pub   4096R/AB17C654 2019-05-30 [expires: 2021-05-29]
# uid                  Open Robotics <info@osrfoundation.org>
cat >"$(etc_apt_trusted_gpg_d)/0xc1cf6e31e6bade8868b172b4f42ed6fbab17c654.asc" <<'EOF'
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQINBFzvJpYBEADY8l1YvO7iYW5gUESyzsTGnMvVUmlV3XarBaJz9bGRmgPXh7jc
VFrQhE0L/HV7LOfoLI9H2GWYyHBqN5ERBlcA8XxG3ZvX7t9nAZPQT2Xxe3GT3tro
u5oCR+SyHN9xPnUwDuqUSvJ2eqMYb9B/Hph3OmtjG30jSNq9kOF5bBTk1hOTGPH4
K/AY0jzT6OpHfXU6ytlFsI47ZKsnTUhipGsKucQ1CXlyirndZ3V3k70YaooZ55rG
aIoAWlx2H0J7sAHmqS29N9jV9mo135d+d+TdLBXI0PXtiHzE9IPaX+ctdSUrPnp+
TwR99lxglpIG6hLuvOMAaxiqFBB/Jf3XJ8OBakfS6nHrWH2WqQxRbiITl0irkQoz
pwNEF2Bv0+Jvs1UFEdVGz5a8xexQHst/RmKrtHLct3iOCvBNqoAQRbvWvBhPjO/p
V5cYeUljZ5wpHyFkaEViClaVWqa6PIsyLqmyjsruPCWlURLsQoQxABcL8bwxX7UT
hM6CtH6tGlYZ85RIzRifIm2oudzV5l+8oRgFr9yVcwyOFT6JCioqkwldW52P1pk/
/SnuexC6LYqqDuHUs5NnokzzpfS6QaWfTY5P5tz4KHJfsjDIktly3mKVfY0fSPVV
okdGpcUzvz2hq1fqjxB6MlB/1vtk0bImfcsoxBmF7H+4E9ZN1sX/tSb0KQARAQAB
tCZPcGVuIFJvYm90aWNzIDxpbmZvQG9zcmZvdW5kYXRpb24ub3JnPokCVAQTAQoA
PhYhBMHPbjHmut6IaLFytPQu1vurF8ZUBQJc7yaWAhsDBQkDwmcABQsJCAcCBhUK
CQgLAgQWAgMBAh4BAheAAAoJEPQu1vurF8ZUkhIP/RbZY1ErvCEUy8iLJm9aSpLQ
nDZl5xILOxyZlzpg+Ml5bb0EkQDr92foCgcvLeANKARNCaGLyNIWkuyDovPV0xZJ
rEy0kgBrDNb3++NmdI/+GA92pkedMXXioQvqdsxUagXAIB/sNGByJEhs37F05AnF
vZbjUhceq3xTlvAMcrBWrgB4NwBivZY6IgLvl/CRQpVYwANShIQdbvHvZSxRonWh
NXr6v/Wcf8rsp7g2VqJ2N2AcWT84aa9BLQ3Oe/SgrNx4QEhA1y7rc3oaqPVu5ZXO
K+4O14JrpbEZ3Xs9YEjrcOuEDEpYktA8qqUDTdFyZrxb9S6BquUKrA6jZgT913kj
J4e7YAZobC4rH0w4u0PrqDgYOkXA9Mo7L601/7ZaDJob80UcK+Z12ZSw73IgBix6
DiJVfXuWkk5PM2zsFn6UOQXUNlZlDAOj5NC01V0fJ8P0v6GO9YOSSQx0j5UtkUbR
fp/4W7uCPFvwAatWEHJhlM3sQNiMNStJFegr56xQu1a/cbJH7GdbseMhG/f0BaKQ
qXCI3ffB5y5AOLc9Hw7PYiTFQsuY1ePRhE+J9mejgWRZxkjAH/FlAubqXkDgterC
h+sLkzGf+my2IbsMCuc+3aeNMJ5Ej/vlXefCH/MpPWAHCqpQhe2DET/jRSaM53US
AHNx8kw4MPUkxExgI7Sd
=4Ofr
-----END PGP PUBLIC KEY BLOCK-----
EOF
if [ "private" = "${use_network:-public}" ]; then
    readonly ros_repo_uri="http://apt.realtime.cxm/apt/ros/${distribution}"
else
    readonly ros_repo_uri="http://packages.ros.org/ros/ubuntu"
fi
readonly ros_atyp_list="$(mktemp -t ros_atyp_list.XXXXXX)"
cat >"${ros_atyp_list}" <<'EOF'
deb
deb-src
EOF
readonly ros_dist_list="$(mktemp -t ros_dist_list.XXXXXX)"
cat >"${ros_dist_list}" <<EOF
${distribution}
EOF
readonly ros_comp_list="$(mktemp -t ros_comp_list.XXXXXX)"
cat >"${ros_comp_list}" <<'EOF'
main
EOF
setup_apt_list \
    "${ros_repo_uri}" \
    "${ros_atyp_list}" \
    "${ros_dist_list}" \
    "${ros_comp_list}"

################################################################################

##########
# UBUNTU #
##########

# pub   1024D/437D05B5 2004-09-12
# uid                  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
# sub   2048g/79164387 2004-09-12
cat >"$(etc_apt_trusted_gpg_d)/0x630239cc130e1a7fd81a27b140976eaf437d05b5.asc" <<'EOF'
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQGiBEFEnz8RBAC7LstGsKD7McXZgd58oN68KquARLBl6rjA2vdhwl77KkPPOr3O
YeSBH/voUsqausJfDNuTNivOfwceDe50lbhq52ODj4Mx9Jg+4aHn9fmRkIk41i2J
3hZiIGPACY/FsSlRq1AhBH2wZG1lQ45W/p77AeARRehYKJP9HY+1h/uihwCgrVE2
VzACJLuZWHbDsPoJaNQjiFcEAKbUF1rMyjd1xJM7bZeXbs8c+ohUo/ywSI/OIr8n
OfUswy08tsCof1KU0JBGLBCn0lHAYkAAcSr2pQ+k/odwdLQSjgm/JcUbi2ll16Wy
7qFbUAUJ5xO+iP61vL3z4pJGcK1pMH6kBLA4CPBchJU/hh3f7vtX2oFdWw8tWqvm
m/W7BACE7h0p86OP2G3ZJBjNYNQTK1LFYa+3G0spsVi9wl+Ih49ImPbSsUc2CSMA
fDlGpYU8FuUKCgQnS3UZz6e0NwrHbZTHBy0ksRwT9jf7qSAEKEN2ECxfwR5i1dU+
Yi4owkqGPhTLAbwkYdZZMcqfGgTXbiU4uy8DzMH/VhqP5wxdwbQ7VWJ1bnR1IEFy
Y2hpdmUgQXV0b21hdGljIFNpZ25pbmcgS2V5IDxmdHBtYXN0ZXJAdWJ1bnR1LmNv
bT6IXgQTEQIAHgUCQUSfPwIbAwYLCQgHAwIDFQIDAxYCAQIeAQIXgAAKCRBAl26v
Q30FtSTNAJ9TwRBI9/dXHqsyx5LkWrPxyO2H7wCfXDY77HnwSK3tTqJzC4m6KuDd
Rhe5Ag0EQUSfRxAIAMglvR9L60xR65i2QG4k2CnqZhmRUaTySxwOlNqKWtokUpzf
8WmqA383uRLO8W9Tee1aF7KEMEUXgFiP7nns0kroKGLlcLbC+nEzkv51ao6Lcr5d
Wr0817LmlvCl2N1KeQDkpHIAiS0LTjuEFY1yosi2ECiOan6sgcLaVqJVbEUeIaYJ
OiZ8O1INTAGGdpVoSPvgkuZVKhP2uMIhYq3qgs6sB5SshEaKAGYIiH3lZ6UJUIVE
uyumxpNPqkJ1Jkpo4SxIwy8KYiQ9Uo1NPP8bmvyGGaeWbRObLPHCO+iqxHxMiE4x
X08sVizxA1YLw9iwtdNPOWkQsM9rn8W/gieH0SsAAwYIAMLzDICy2IA1wcmf5XPp
g4JBFuMjeg8pIuaQZMf/MO2u+RlOVrIXPVFtYOpxQR9C1gCg+Blg2qQXBNw19cNT
2EtSGi0HtycTww2xnIOnaLOzq/eI/LnakdAMclaTVbNltraepkoRFE4Exvuq/tCd
zssotnmAha1tzGf+O3QyxkIBJ6zHFTNCREGBPYi/Pe9iviWqNAIr3SPhlw7STFrV
Dgpne9VdpOZb3nVYYQHG6iwvVwzrE23+84RMFENq4Dhyx9L8R6+PMt347uT8dB03
PXMovOpwXX06zMgfGwF60TZsmHqun/E3gE46YiME26rmUX5KSNTm9N2IZA8jz/sF
Xz2ISQQYEQIACQUCQUSfRwIbDAAKCRBAl26vQ30FtdxYAJsFjU+xbex7gevyGQ2/
mhqidES4MwCggqQyo+w1Twx6DKLF+3rF5nf1F3Q=
=2m5N
-----END PGP PUBLIC KEY BLOCK-----
EOF

# pub   4096R/C0B21F32 2012-05-11
# uid                  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>
cat >"$(etc_apt_trusted_gpg_d)/0x790bc7277767219c42c86f933b4fe6acc0b21f32.asc" <<'EOF'
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQINBE+tgXgBEADfiL1KNFHT4H4Dw0OR9LemR8ebsFl+b9E44IpGhgWYDufj0gaM
/UJ1Ti3bHfRT39VVZ6cv1P4mQy0bnAKFbYz/wo+GhzjBWtn6dThYv7n+KL8bptSC
Xgg1a6en8dCCIA/pwtS2Ut/g4Eu6Z467dvYNlMgCqvg+prKIrXf5ibio48j3AFvd
1dDJl2cHfyuON35/83vXKXz0FPohQ7N7kPfI+qrlGBYGWFzC/QEGje360Q2Yo+rf
MoyDEXmPsoZVqf7EE8gjfnXiRqmz/Bg5YQb5bgnGbLGiHWtjS+ACIdLUq/h+jlSp
57jw8oQktMh2xVMX4utDM0UENeZnPllVJSlR0b+ZmZz7paeSar8Yxn4wsNlL7GZb
pW5A/WmcmWfuMYoPhBo5Fq1V2/siKNU3UKuf1KH+X0p1oZ4oOcZ2bS0Zh3YEG8IQ
ce9Bferq4QMKsekcG9IKS6WBIU7BwaElI2ILD0gSwu8KzvNSEeIJhYSsBIEzrWxI
BXoN2AC9PCqqXkWlI5Xr/86RWllB3CsoPwEfO8CLJW2LlXTen/Fkq4wT+apdhHei
WiSsq/J5OEff0rKHBQ3fK7fyVuVNrJFb2CopaBLyCxTupvxs162jjUNopt0c7OqN
BoPoUoVFAxUSpeEwAw6xrM5vROyLMSeh/YnTuRy8WviRapZCYo6naTCY5wARAQAB
tEJVYnVudHUgQXJjaGl2ZSBBdXRvbWF0aWMgU2lnbmluZyBLZXkgKDIwMTIpIDxm
dHBtYXN0ZXJAdWJ1bnR1LmNvbT6JAjgEEwECACIFAk+tgXgCGwMGCwkIBwMCBhUI
AgkKCwQWAgMBAh4BAheAAAoJEDtP5qzAsh8yXX4QAJHUdK6eYMyJcrFP3yKXtUYQ
MpaHRM/floqZtOFhlmcLVMgBNOr0eLvBU0JcZyZpHMvZciTDBMWX8ItCYVjRejf0
K0lPvHHRGaE7t6JHVUCeznNbDMnOPYVwlVJdZLOa6PmE5WXVXpk8uTA8vm6RO2rS
23vE7U0pQlV+1GVXMWH4ZLjaQs/Tm7wdvRxeqTbtfOEeHGLjmsoh0erHfzMV4wA/
9Zq86WzuJS1HxXR6OYDC3/aQX7CxYT1MQxEw/PObnHtkl3PRMWdTW7fSQtulEXzp
r2/JCev6Mfc8Uy0aD3jng9byVk9GpdNFEjGgaUqjqyZosvwAZ4/dmRjmMEibXeNU
GC8HeWC3WOVV8L/DiA+miJlwPvwPiA1ZuKBI5A8VF0rNHW7QVsG8kQ+PDHgRdsmh
pzSRgykN1PgK6UxScKX8LqNKCtKpuEPApka7FQ1u4BoZKjjpBhY1R4TpfFkMIe7q
W8XfqoaP99pED3xXch2zFRNHitNJr+yQJH4z/o+2UvnTA2niUTHlFSCBoU1MvSq1
N2J3qU6oR2cOYJ4ZxqWyCoeQR1x8aPnLlcn4le6HU7TocYbHaImcIt7qnG4Ni0OW
P4giEhjOpgxtrWgl36mdufvriwya+EHXzn36EvQ9O+bm3fyarsnhPe01rlsRxqBi
K1JOw/g4GnpX8iLGEX1V
=t8OL
-----END PGP PUBLIC KEY BLOCK-----
EOF
if [ "private" = "${use_network:-public}" ]; then
    readonly ubuntu_repo_uri="http://apt.realtime.cxm/apt/ubuntu/${distribution}"
else
    readonly ubuntu_repo_uri="http://archive.ubuntu.com/ubuntu"
fi
readonly ubuntu_atyp_list="$(mktemp -t ubuntu_atyp_list.XXXXXX)"
cat >"${ubuntu_atyp_list}" <<'EOF'
deb
deb-src
EOF
readonly ubuntu_dist_list="$(mktemp -t ubuntu_dist_list.XXXXXX)"
cat >"${ubuntu_dist_list}" <<EOF
${distribution}
${distribution}-backports
${distribution}-security
${distribution}-updates
EOF
readonly ubuntu_comp_list="$(mktemp -t ubuntu_comp_list.XXXXXX)"
cat >"${ubuntu_comp_list}" <<'EOF'
main
restricted
universe
multiverse
EOF
setup_apt_list \
    "${ubuntu_repo_uri}" \
    "${ubuntu_atyp_list}" \
    "${ubuntu_dist_list}" \
    "${ubuntu_comp_list}"

##############
# UBUNTU END #
##############

# proactive protection against a bad proxy
#
# * https://askubuntu.com/questions/679233/failed-to-fetch-hash-sum-mismatch-tried-rm-apt-list-but-didnt-work
# * https://serverfault.com/questions/722893/debian-mirror-hash-sum-mismatch
# * https://gist.github.com/trastle/5722089
info "install $(etc_apt_apt_conf_d)/99fixbadproxy"
cat >"$(etc_apt_apt_conf_d)/99fixbadproxy" <<'FIXBADPROXY'
Acquire::http::Pipeline-Depth "0";
Acquire::http::No-Cache=True;
Acquire::BrokenProxy=true;
FIXBADPROXY

exit "$?"
