#!/bin/sh

# scrippies/docker-catkin

set -euvx

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly whatami="$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

log() { echo "${whatami}[$$]: $*" >&2; }
error() { log "ERROR: $*"; }
warning() { log "WARNING: $*"; }
info() { log "INFO: $*"; }

die() {
    error "$*"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}"
    if command -v docker >/dev/null 2>&1; then
        docker system prune --force --filter until=6h >&2 || true
    fi
    return "${status}"
}

usage() {
    cat <<EOF
Usage: $0 [OPTION]...
Dockerize catkin build, catkin run_tests, and catkin_test_results.

Options:

    -h                 print usage and exit
    -C CATKIN_WS       run as if started in CATKIN_WS (default: \$PWD)
    -D DISTRIBUTION    ubuntu distribution (default: inferred/detected)
    -R ROS_DISTRO      ros distribution (default: inferred/detected)

Examples:

    \$ $0

    \$ $0 -C \$HOME/catkin_ws

    \$ $0 -C \$HOME/catkin_ws -D bionic

    \$ $0 -C \$HOME/catkin_ws -D bionic -R melodic

EOF
}

infer_distribution() {
    case "${ros_distro:-}" in
        kinetic)
            echo "xenial"
            return 0
            ;;
        melodic)
            echo "bionic"
            return 0
            ;;
        "")
            error "undefined ros_distro"
            return 1
            ;;
        *)
            error "unknown ros_distro: ${ros_distro}"
            return 1
            ;;
    esac
}

infer_ros_distro() {
    case "${distribution:-}" in
        xenial)
            echo "kinetic"
            return 0
            ;;
        bionic)
            echo "melodic"
            return 0
            ;;
        "")
            error "undefined distribution"
            return 1
            ;;
        *)
            error "unknown distribution: ${distribution}"
            return 1
            ;;
    esac
}

detect_distribution() {
    if ! [ -f /etc/os-release ]; then
        error "missing file: /etc/os-release"
        return 1
    fi
    # shellcheck disable=SC1091
    . /etc/os-release
    if [ -z "${VERSION_CODENAME:-}" ]; then
        error "undefined VERSION_CODENAME"
        return 1
    fi
    echo "${VERSION_CODENAME}"
}

# take nothing and detect the installed ros_distro; print ros_distro on
# success; print nothing on failure
detect_ros_distro() {
    if ! [ -d /opt/ros ]; then
        error "missing directory: /opt/ros"
        return 1
    fi
    # shellcheck disable=SC2039
    local ros_distro_list=""
    ros_distro_list="$(mktemp -t ros.distro.list.XXXXXX)"
    find /opt/ros -maxdepth 1 -mindepth 1 -type d -exec basename {} \; >"${ros_distro_list}"
    case "$(wc -l <"${ros_distro_list}")" in
        0)
            error "missing ROS installation"
            return 1
            ;;
        1)
            cat "${ros_distro_list}"
            return 0
            ;;
        *)
            error "multiple ROS installations"
            return 1
            ;;
    esac
}

# Print a sha1 for the current state of the checkout.
#
# When there are uncommitted changes, `git stash create` will make a commit
# object (without storing it) and print it. When there are no uncommitted
# changes, `git stash create` will print an empty string and succeed; in this
# case we want get sha1sum of the HEAD. We attempt to print both, but take only
# the first.
#
# $1 : git checkout directory
get_vcs_ref() {
    (
        git -C "$1" stash create
        git -C "$1" rev-parse HEAD
    ) | head -1
}

# Copy given git checkout directory into optional destination directory using
# `git archive`.
#
# reference:
# https://git-scm.com/docs/git-submodule#git-submodule-foreach--recursiveltcommandgt
#
# $1 : git checkout directory
# $2 : target directory (default: $PWD)
gitcopy() {
    git -C "$1" archive "$(get_vcs_ref "$1")" \
        | tar -C "${2:-${PWD}}" -xf-
    git -C "$1" submodule foreach --recursive --quiet \
        "git archive --prefix=\${sm_path}/ \${sha1} | tar -C ${2:-${PWD}} -xf-"
}

ttcopy() {
    tar -C "$1" -cf- . | tar -C "${2:-${PWD}}" -xf-
}

# Copy given source directory contents into optional destination directory. If
# `git` is present and source directory is a git checkout, then use `gitcopy`;
# else use `ttcopy`.
#
# $1 : source directory
# $2 : target directory (default: $PWD)
dircopy() {
    if command -v git >/dev/null 2>&1; then
        if git -C "$1" status >/dev/null 2>&1; then
            gitcopy "$1" "${2:-${PWD}}"
            return "$?"
        fi
    fi
    ttcopy "$1" "${2:-${PWD}}"
}

# takes a source directory and a target directory; operates on the catkin
# workspace currently residing at target directory; mutates files therein to
# change source references to target references.
#
# $1 : source directory
# $2 : target directory
catkin_ws_pathfix() {
    # shellcheck disable=SC2039
    local source_dir="$1"
    # shellcheck disable=SC2039
    local target_dir="$2"
    find \
        "${target_dir}/.catkin_tools" \
        "${target_dir}/build" \
        "${target_dir}/devel" \
        "${target_dir}/install" \
        "${target_dir}/logs" \
        -type f \
        -exec grep -qI "${source_dir}" {} + \
        -exec sed -i "s|${source_dir}|${target_dir}|g" {} + \
        || true
}

# https://stackoverflow.com/questions/23513045/how-to-check-if-a-process-is-running-inside-docker-container
# https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker
is_in_container() { grep -q 'lxc\|docker' /proc/1/cgroup; }

catkin_verb() {
    catkin "$@" \
        --no-color \
        --no-notify \
        --no-status \
        --summarize \
        --verbose \
        --cmake-args \
        -DCMAKE_CPP_FLAGS="${CPPFLAGS:-}" \
        -DCMAKE_CXX_COMPILER="${CXX:-$(command -v c++)}" \
        -DCMAKE_CXX_FLAGS="${CXXFLAGS:-}" \
        -DCMAKE_C_COMPILER="${CC:-$(command -v cc)}" \
        -DCMAKE_C_FLAGS="${CFLAGS:-}" \
        -DCMAKE_VERBOSE_MAKEFILE=true \
        -- \
        --make-args \
        "${MAKEFLAGS:- --jobs=$((($(nproc)+1)/2)) --load-average=$(nproc)}" \
        --
}

# $1 : catkin_ws
#
# take catkin_ws and vet it; for good catkin_ws, print it and return success;
# otherwise, print nothing and return failure
vet_catkin_ws() {
    # shellcheck disable=SC2039
    local result=""
    if ! result="$(readlink -f "$1")"; then
        error "bad path: $1"
        return 1
    fi
    if ! [ -d "${result}" ]; then
        error "not a directory: ${result}"
        return 1
    fi
    if ! [ -d "${result}/src" ]; then
        error "not a directory: ${result}/src"
        return 1
    fi
    echo "${result}"
    return 0
}

vet_root_script() {
    # shellcheck disable=SC2039
    local result=""
    if ! result="$(readlink -f "$1")"; then
        error "bad path: $1"
        return 1
    fi
    if ! [ -x "${result}" ]; then
        warning "not executable: ${result}"
        if ! chmod -v +x "${result}" >&2; then
            error "FAILURE: chmod -v +x ${result}"
            return 1
        fi
    fi
    echo "${result}"
    return 0
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

while getopts ":hC:D:R:" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        C)
            if ! catkin_ws="$(vet_catkin_ws "${OPTARG}")"; then
                die "FAILURE: vet_catkin_ws ${OPTARG}"
            fi
            readonly catkin_ws="${catkin_ws}"
            ;;
        D) readonly distribution="${OPTARG}" ;;
        R) readonly ros_distro="${OPTARG}" ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((OPTIND - 1))"

# catkin_ws
if [ -n "${catkin_ws:-}" ]; then
    info "catkin_ws: ${catkin_ws}"
else
    if ! catkin_ws="$(vet_catkin_ws "${PWD}")"; then
        die "failure: vet_catkin_ws ${PWD}"
    fi
    readonly catkin_ws="${catkin_ws}"
    warning "defaulting catkin_ws: ${catkin_ws}"
fi

# distribution
if [ -n "${distribution:-}" ]; then
    info "distribution: ${distribution}"
elif distribution="$(infer_distribution)"; then
    readonly distribution="${distribution}"
    warning "inferred distribution: ${distribution}"
elif distribution="$(detect_distribution)"; then
    readonly distribution="${distribution}"
    warning "detected distribution: ${distribution}"
else
    die "failed to get, infer, and/or detect distribution"
fi

# ros_distro
if [ -n "${ros_distro:-}" ]; then
    info "ros_distro: ${ros_distro}"
elif ros_distro="$(infer_ros_distro)"; then
    readonly ros_distro="${ros_distro}"
    warning "inferred ros_distro: ${ros_distro}"
elif ros_distro="$(detect_ros_distro)"; then
    readonly ros_distro="${ros_distro}"
    warning "detected ros_distro: ${ros_distro}"
else
    die "failed to get, infer, and/or detect ros_distro"
fi

################################################################################

if ! tty; then
    # no tty, so abuse `script` to get one
    # https://stackoverflow.com/questions/32910661/pretend-to-be-a-tty-in-bash-for-any-command/32981392#32981392
    script -qfec "${this} -C ${catkin_ws} -D ${distribution} -R ${ros_distro}" /dev/null
    exit "$?"
fi

########################
# NOW RUNNING WITH TTY #
########################

if ! is_in_container; then
    # We build stuff under $TMPDIR. Sometimes, the build requires the
    # extraction of tarballs. Extracting tarballs on OverlayFS is, apparently,
    # full of fail (https://github.com/moby/moby/issues/19647). This is
    # especially problematic because the default backing store for docker is
    # OverlayFS.
    #
    # To get around the OverlayFS issue, we need to bind-mount the host $TMPDIR
    # to the container $TMPDIR. To isolate the current build from others like
    # it, we first override $TMPDIR to a location specific to the current
    # build.
    #
    # Also, there's a prevailing assumption that source will be built within
    # the home directory of the user executing the build. To satisfy this
    # assumption within the container, we create a luser with HOME=$TMPDIR .
    readonly image_name="registry.gitlab.com/realtime-robotics/ros-dpkg:${ros_distro}"
    if [ "true" = "${DOCKER_IMAGE_PULL:-false}" ] \
        || ! docker image inspect "${image_name}" >/dev/null 2>&1; then
        docker image pull "${image_name}"
    else
        warning "skipping: docker image pull ${image_name}"
    fi
    docker image inspect "${image_name}"

    readonly host_memory_k="$(grep -Eom1 '[0-9]+' /proc/meminfo)"
    readonly docker_workdir="$(mktemp -ut docker_workdir.XXXXXX)"
    docker container run \
        --cpus "$((($(nproc) + 3) / 4))" \
        --env CATKIN_WS="${catkin_ws}" \
        --env DEBCONF_NONINTERACTIVE_SEEN=true \
        --env DEBIAN_FRONTEND=noninteractive \
        --env DISTRIBUTION="${distribution}" \
        --env DOCKER_HOST_GID="$(id -g)" \
        --env DOCKER_HOST_UID="$(id -u)" \
        --env HERE="${here}" \
        --env NO_COLOR="${NO_COLOR:-1}" \
        --env ROS_DISTRO="${ros_distro}" \
        --env SUDO_FORCE_REMOVE=yes \
        --env TERM=dumb \
        --env THIS="${this}" \
        --interactive \
        --memory "$((host_memory_k / 2))k" \
        --memory-swap "${host_memory_k}k" \
        --memory-swappiness 100 \
        --mount type=bind,readonly,source="${here}",target="${here}" \
        --mount type=bind,source="${PWD}",target="${docker_workdir}" \
        --mount type=bind,source="${catkin_ws}",target="${catkin_ws}" \
        --mount type=bind,source="${tmpdir}",target="${tmpdir}" \
        --rm \
        --tty \
        --workdir "${docker_workdir}" \
        "${image_name}" sh -c "${this} -C ${catkin_ws} -D ${distribution} -R ${ros_distro}"
    exit "$?"
fi

############################
# NOW INSIDE THE CONTAINER #
############################

if [ 0 -eq "$(id -u)" ]; then
    # running as root; set up for luser invocation

    # maybe someday:
    #dpkg-divert --local --rename /bin/bash

    dpkg-divert --local --rename /usr/bin/git

    # nuke existing apt state, configure apt, and re-populate apt state
    find /etc/apt/sources.list.d /var/lib/apt/lists -type f \
        -exec rm -vf /etc/apt/sources.list {} +
    "${here}/configure-apt"
    apt-get -y update

    # For the packages that need it, we need to mung rosdep *BEFORE* the luser
    # does a `rosdep update`. There's no good way to know which apt repository
    # contains which packages that need rosdep fakery to masquerade as ROS
    # packages -- we need _a priori_ knowledge to effect this "whitelist".

    # Will wants freecad packages in rosdep
    readonly freecad_pkg_list="$(mktemp -t freecad_pkg_list.XXXXXX)"
    # https://www.debian.org/doc/manuals/debian-reference/ch02.en.html#_fetching_of_the_meta_data_for_the_package
    find /var/lib/apt/lists -maxdepth 1 -type f \
        -name "*freecad*_dists_${distribution}_*_binary-$(dpkg --print-architecture)_Packages*" \
        -exec /usr/lib/apt/apt-helper cat-file {} + >"${freecad_pkg_list}"
    sed -nri 's|^Package: ([[:graph:]]+)|\1|gp' "${freecad_pkg_list}"
    sort -uo "${freecad_pkg_list}" "${freecad_pkg_list}"
    cat -n "${freecad_pkg_list}" >&2
    while read -r freecad_pkg; do
        "${here}/configure-rosdep" "${freecad_pkg}"
    done <"${freecad_pkg_list}"

    # create luser account
    groupadd -g "${DOCKER_HOST_GID}" luser
    useradd -m -u"${DOCKER_HOST_UID}" -g"${DOCKER_HOST_GID}" -s"$(command -v sh)" luser

    # STUPID ROS: rosdep invokes sudo apt-get to install things
    apt-get -y --no-install-recommends install sudo
    cat >/etc/sudoers.d/luser-apt-get <<LUSER_APT_GET
luser $(hostname) = (root) NOPASSWD: $(command -v apt-get)
LUSER_APT_GET

    # http://wiki.ros.org/rosdep#Install_dependency_of_all_packages_in_the_workspace
    nice -n19 su luser <<'SU_LUSER'
set -euvx
rosdep update --verbose
rosdep install \
    --default-yes \
    --from-path "${CATKIN_WS}/src" \
    --ignore-packages-from-source \
    --verbose
SU_LUSER

    # STUPID ROS: now de-sudo luser
    rm -vf /etc/sudoers.d/luser-apt-get

    # because pcl_ros has too many shared objects
    pclros_config_cmake="/opt/ros/${ros_distro}/share/pcl_ros/cmake/pcl_rosConfig.cmake"
    if [ -f "${pclros_config_cmake}" ]; then
        sed -r \
            -i.backup \
            -e 's,;/usr/include/vtk[[:alnum:].-]+,,g' \
            -e 's,;/usr/lib(/x86_64-linux-gnu)?/libvtk[[:alnum:].-]+,,g' \
            "${pclros_config_cmake}"
        if diff "${pclros_config_cmake}.backup" "${pclros_config_cmake}"; then
            warning: "FUTZING DID NOT CHANGE ANYTHING: ${pclros_config_cmake}"
        fi
    fi

    if command -v npm; then
        "${here}/configure-npm"
    fi

    nice -n19 su -c "${this} -C ${catkin_ws} -D ${distribution} -R ${ros_distro}" luser
    exit "$?"
fi

########################
# NOW RUNNING AS LUSER #
########################

env | sort
rosdep update --verbose
# catkin init --workspace "${catkin_ws}" --reset
catkin config --workspace "${catkin_ws}" --extend "/opt/ros/${ros_distro}" --install
catkin clean --workspace "${catkin_ws}" --yes
catkin_verb build --workspace "${catkin_ws}"
catkin_verb run_tests --workspace "${catkin_ws}"
result=""
(
    # because ROS stupidly expands undefined variables, but we still need to
    # collect test results failures
    set +eu
    # shellcheck disable=SC1090
    . "/opt/ros/${ros_distro}/setup.sh"
    catkin_test_results "${catkin_ws}"
) && result="$?" || result="$?"

symlinks -cdrs "${catkin_ws}"

exit "${result}"
