#!/bin/sh

set -euvx

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly whatami="$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

log() { echo "${whatami}[$$]: $@" >&2; }
error() { log "ERROR: $@"; }
warning() { log "WARNING: $@"; }
info() { log "INFO: $@"; }

usage() {
    cat <<EOF
Usage: $0 [OPTION]... [PACKAGE]...
Build the given golang package[s] into static binaries.

Options
    -h                 print this usage and return success

Examples:

    \$ $0 -h

    \$ $0 mvdan.cc/sh/cmd/shfmt

    \$ $0 go.universe.tf/netboot/cmd/pixiecore

EOF
}

die() {
    error "$@"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}"
    if command -v docker >&2; then
        docker system prune --force --filter until=6h >&2 || true
    fi
    return "${status}"
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

while getopts ":h" opt; do
    case "${opt}" in
        h)
            usage
            exit "$?"
            ;;
        :) die "Missing argument: -${OPTARG}" ;;
        \?) die "Invalid option: -${OPTARG}" ;;
    esac
done
shift "$((${OPTIND} - 1))"

# https://stackoverflow.com/questions/23513045/how-to-check-if-a-process-is-running-inside-docker-container
# https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker
if ! grep -q 'lxc\|docker' /proc/1/cgroup; then
    readonly image_name="${whatami}"
    docker build --tag "${image_name}" --file - "${here}" <<'EOF'
FROM golang:alpine
WORKDIR /tmp
RUN apk add --update gcc git musl-dev
EOF

    readonly workdir="$(mktemp -ut workdir.XXXXXX)"
    docker container run \
        --env GOCACHE=/tmp \
        --interactive \
        --mount type=bind,readonly,source="${this}",target="${this}" \
        --mount type=bind,source="${PWD}",target="${workdir}" \
        --rm \
        --user "$(id -u):$(id -g)" \
        --workdir "${workdir}" \
        "${image_name}" sh -c "${this} $@"
    exit "$?"
fi

for pkg in $@; do
    /usr/local/go/bin/go get -v -d "${pkg}/..."
    /usr/local/go/bin/go build -a -buildmode=pie -ldflags='-linkmode external -extldflags "-static"' "${pkg}"
done
