#!/bin/sh

set -euvx

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly whatami="$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

readonly default_deb_url="http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo/pool/xenial/main/librscalibrationapi_2.6.8.0_amd64.deb"
readonly default_pkg_dir="/var/packages"

log() { echo "${whatami}[$$]: $@" >&2; }
error() { log "ERROR: $@"; }
warning() { log "WARNING: $@"; }
info() { log "INFO: $@"; }

die() {
    error "$@"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}" || true
    return "${status}"
}

usage() {
    cat <<EOF
Usage: $0 [OPTION]...
Download, tweak, and install librscalibrationapi and various references thereto.

Options
    -h            print this usage and return success
    -C PKG_DIR    override PKG_DIR (default: ${default_pkg_dir})
    -u DEB_URL    override DEB_URL (default: ${default_deb_url})

Examples:

    \$ $0 -h

    \$ $0

    \$ $0 -C ${default_pkg_dir}

    \$ $0 -C ${default_pkg_dir} -u ${default_deb_url}

EOF
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

while getopts ":hC:u:" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        C) readonly pkg_dir="${OPTARG}" ;;
        u) readonly deb_url="${OPTARG}" ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((${OPTIND} - 1))"

# vet opts
if [ -n "${pkg_dir:-}" ]; then
    info "given pkg_dir: ${pkg_dir}"
else
    readonly pkg_dir="${default_pkg_dir}"
    warning "defaulting pkg_dir: ${pkg_dir}"
fi
if [ -n "${deb_url:-}" ]; then
    info "given deb_url: ${deb_url}"
else
    readonly deb_url="${default_deb_url}"
    warning "defaulting deb_url: ${deb_url}"
fi

(
    cd "${pkg_dir}"
    curl -fsSLO "${deb_url}"
    deb_file="${PWD}/$(basename "${deb_url}")"
    deb_dir="${deb_file%.deb}"
    # extract, remove references to libpng*, delete executables, delete
    # examples, delete empty directories, and rebuild
    dpkg-deb --raw-extract "${deb_file}" "${deb_dir}"
    sed -ri '/^Depends: /s/libpng[^,]+[, ]*//g' "${deb_dir}/DEBIAN/control"
    find "${deb_dir}" -type f -perm /111 -exec rm -vf {} \;
    find "${deb_dir}" -type d -name 'examples' | xargs -r rm -vrf
    find "${deb_dir}" -type d -empty -delete
    dpkg-deb --build "${deb_dir}" "${deb_file}"
    rm -rf "${deb_dir}"
)

exit "$?"
