#!/bin/sh

# scrippies/lawyer-chow

set -eu

this="$(readlink -f "$0")"
readonly this="${this}"
here="$(dirname "${this}")"
readonly here="${here}"
whatami="$(basename "${this}")"
readonly whatami="${whatami}"
tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
readonly tmpdir="${tmpdir}"

default_outfile="lawyer-chow.tar.xz"
readonly default_outfile="${default_outfile}"

log() { echo "${whatami}[$$]: $*" >&2; }
error() { log "ERROR: $*"; }
warning() { log "WARNING: $*"; }
info() { log "INFO: $*"; }

die() {
    error "$@"
    usage >&2
    exit 1
}

cleanup() {
    # shellcheck disable=SC3043
    local status="$?"
    rm -rf "${tmpdir}"
    return "${status}"
}

usage() {
    cat <<EOF

Usage: $0 [OPTION]... PACKAGE_NAME
Make lawyer chow for the given package.

Options:

    -h    print this usage and return success

Examples:

    \$ $0 rapidplan

EOF
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

while getopts ":h" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((OPTIND - 1))"

################################################################################

depends_list="$(mktemp -t depends_list.XXXXXX)"
readonly depends_list="${depends_list}"
# shellcheck disable=SC2016
dpkg-query --show --showformat '${Depends}' "$1" >"${depends_list}"
sed -i 's/, /\n/g' "${depends_list}"
sed -ri 's/^([[:graph:]]+).*/\1/g' "${depends_list}"
sort -uo "${depends_list}" "${depends_list}"

echo 'Package,Version,Maintainer,Homepage,License'
while read -r pkg; do
    {
        dpkg-query \
            --show \
            --showformat '#${Package},#${Version},#${Maintainer},#${Homepage},#' \
            "${pkg}"
        "${here}/dpkg-licenses" "${pkg}" || echo "NA"
    } | sed -r 's/#,/NA,/g;s/#//g'
done <"${depends_list}"

exit "$?"
