#!/bin/sh

# scrippies/repolizer

set -euvx

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly whatami="$(basename "${here}").$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

readonly default_distribution="xenial"

log() { echo "${whatami}[$$]: $@" >&2; }
error() { log "ERROR: $@"; }
warning() { log "WARNING: $@"; }
info() { log "INFO: $@"; }

die() {
    error "$@"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}"
    return "${status}"
}

usage() {
    cat <<EOF
Usage: $(basename ${this}) [OPTION]...
Make current working directory an apt repository with resolved dependencies.

Options:
    -h                 print this usage and return success
    -C WORKDIR         run as if started in WORKDIR
    -D DISTRIBUTION    override distribution (default: ${default_distribution})

Examples:

    \$ $(basename ${this})

    \$ $(basename ${this}) -C \$PWD

    \$ $(basename ${this}) -C \$PWD -D xenial

EOF
}

# $1 : start node
# $2 : edge list
traverse() {
    if grep -q "^$1" <"$2"; then
        grep "^$1" <"$2" | while read curr next; do
            traverse "${next}" "$2"
        done
    else
        echo "$1"
    fi
}

# Kosaraju's algorithm for finding strongly connected components
#
# $1 : adjacency list of edges
kosaraju_scc() {
    readonly edges="$(mktemp -t edges.XXXXXX)"
    cat >"${edges}" <"${1:-/dev/stdin}"

    # create the topological sort; save stderr to find cycles
    readonly tsort_out="$(mktemp -t tsort_out.XXXXXX)"
    readonly tsort_err="$(mktemp -t tsort_err.XXXXXX)"
    tsort <"${edges}" >"${tsort_out}" 2>"${tsort_err}" || true

    # remove edges that comprise cycles
    sed -nr 's|^tsort: ([[:graph:]]+)$|\1|gp' "${tsort_err}" \
        | xargs -I{} sed -i "/^{}/d" "${edges}"
    
    # transpose edges to create reverse edges
    readonly redges="$(mktemp -t redges.XXXXXX)"
    sed -r 's|^([[:graph:]]+)([[:space:]]+)([[:graph:]]+)$|\3\2\1|g' <"${edges}" >"${redges}"
    
    # in topological order, traverse the graph of reversed edges; print every
    # dead end
    while read pkg; do
        traverse "${pkg}" "${redges}";
    done <"${tsort_out}" | sort -u
}

run_raw() {
    # make a fake apt configuration that a luser can work
    readonly fake_apt_dir="$(mktemp -dt fake_apt_dir.XXXXXX)"
    tar -cf- -C / etc/apt var/lib/apt var/cache/apt | tar -xf- -C "${fake_apt_dir}"
    export APT_CONFIG="${fake_apt_dir}/etc/apt/apt.conf"
    cat >"${APT_CONFIG}" <<EOF
Dir "${fake_apt_dir}";
EOF

    # make a fake apt repo in workdir
    (
        cd "${workdir}"
        dpkg-scanpackages --multiversion . >Packages
        cat >"${fake_apt_dir}/etc/apt/sources.list.d/$(echo "${PWD}" | tr -s '/' '_').list" <<EOF
deb     [trusted=yes] file://${PWD} ./
EOF
    )

    # enumerate the list of scanned packages
    readonly package_list="$(mktemp -t package_list.XXXXXX)"
    sed -nr 's|^Package: (.*)$|\1|gp' "${workdir}/Packages" >"${package_list}"

    # from the list of scanned packages, enumerate recursive dependencies
    # https://stackoverflow.com/questions/22008193/how-to-list-download-the-recursive-dependencies-of-a-debian-package/41428445#41428445
    readonly depends_list="$(mktemp -t depends_list.XXXXXX)"
    apt-get -y update >&2
    sed -nr 's|^Package: (.*)$|\1|gp' "${workdir}/Packages" \
        | xargs apt-cache depends \
            --recurse \
            --no-recommends \
            --no-suggests \
            --no-conflicts \
            --no-breaks \
            --no-replaces \
            --no-enhances \
            --no-pre-depends \
            <"${package_list}" >"${depends_list}"

    # > Package names (both source and binary, see Package) must consist only
    # > of lower case letters (a-z), digits (0-9), plus (+) and minus (-)
    # > signs, and periods (.). They must be at least two characters long and
    # > must start with an alphanumeric character.
    #
    # https://www.debian.org/doc/debian-policy/ch-controlfields.html#source
    sed -nri '/^[[:alnum:]][[:alnum:].+-]+$/p' "${depends_list}"
    sort -uo "${depends_list}" "${depends_list}"

    (
        cd "${workdir}"
        xargs apt-get download <"${depends_list}"

        # again, because we (may) have added packages
        dpkg-scanpackages --multiversion . >Packages
    )

    # re-enumerate the scanned packages
    sed -nr 's|^Package: (.*)$|\1|gp' "${workdir}/Packages" >"${package_list}"

    # generate the dependency graph
    readonly depend_edges="$(mktemp -t depend_edges.XXXXXX)"
    while read pkg; do
        apt-cache depends "${pkg}" \
            | sed -nr 's|^  Depends: (.*)$|\1|gp' \
            | while read dep; do
            echo "${pkg} ${dep}"
        done
    done <"${package_list}" >"${depend_edges}"

    # generate the list of "strongly connected component" packages
    kosaraju_scc <"${depend_edges}" >"${workdir}/install-list.txt"
}

run_dockerized() {
    readonly image_name="ubuntu:${distribution}"
    if [ "true" = "${DOCKER_IMAGE_PULL:-false}" ]; then
        docker image pull "${image_name}"
    else
        warning "skipping: docker image pull ${image_name}"
    fi

    docker container run \
        --env DEBCONF_NONINTERACTIVE_SEEN=true \
        --env DEBIAN_FRONTEND=noninteractive \
        --env DISTRIBUTION="${distribution}" \
        --env DOCKER_HOST_GID="$(id -g)" \
        --env DOCKER_HOST_UID="$(id -u)" \
        --env HERE="${here}" \
        --env THIS="${this}" \
        --env WORKDIR="${workdir}" \
        --interactive \
        --mount type=bind,readonly,source="${here}",target="${here}" \
        --mount type=bind,source="${workdir}",target="${workdir}" \
        --rm \
        --workdir "${workdir}" \
        "${image_name}" sh <<'EOF'
set -euvx
apt-get -y update
apt-get -y --no-install-recommends install dpkg-dev
"${HERE}/configure-apt" "${DISTRIBUTION}"

groupadd -g "${DOCKER_HOST_GID}" luser
useradd \
    -u "${DOCKER_HOST_UID}" \
    -g "${DOCKER_HOST_GID}" \
    -d "$(mktemp -dt home.luser.XXXXXX)" \
    -s "$(command -v sh)" \
    luser

nice -n19 su -c "${THIS} -r -C ${WORKDIR} -D ${DISTRIBUTION}" luser
EOF
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

while getopts ":hrC:D:" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        r) readonly run_raw="true" ;;
        C)
            if ! workdir="$(readlink -f "${OPTARG}")"; then
                die "missing: ${OPTARG}"
            fi
            if ! [ -d "${workdir}" ]; then
                die "not a directory: ${workdir}"
            fi
            readonly workdir="${workdir}"
            ;;
        D) readonly distribution="${OPTARG}" ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((${OPTIND} - 1))"

if [ -n "${distribution:-}" ]; then
    info "distribution: ${distribution}"
else
    readonly distribution="${default_distribution}"
    warning "defaulting distribution: ${distribution}"
fi

if [ -n "${workdir:-}" ]; then
    info "workdir: ${workdir}"
else
    readonly workdir="${PWD}"
    warning "defaulting workdir: ${workdir}"
fi

if [ "true" = "${run_raw:-false}" ]; then
    run_raw
else
    run_dockerized
fi

exit "$?"
