#!/bin/sh

# scrippies/ros-gensymbols

set -eu

this="$(readlink -f "$0")"
readonly this="${this}"
whatami="$(basename "${this}")"
readonly whatami="${whatami}"
tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
readonly tmpdir="${tmpdir}"

log() { echo "${whatami}[$$]: $*" >&2; }
error() { log "ERROR: $*"; }
warning() { log "WARNING: $*"; }
info() { log "INFO: $*"; }

die() {
    error "$@"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}" || true
    return "${status}"
}

usage() {
    cat <<EOF

Usage: $0 [OPTION]...
Generate a symbols file for every ROS shared object.

Options:

    -h               print usage and exit
    -R ROS_DISTRO    override ros_distro (detected by default)

Examples:

    \$ $0
 
    \$ $0 -R focal

EOF
}

# take nothing and detect the installed ros_distro; print ros_distro on
# success; print nothing on failure
detect_ros_distro() {
    find /opt/ros -maxdepth 1 -mindepth 1 -type d -exec basename -a {} + \
        | paste -sd, \
        | grep -Eox '[[:lower:]]{4,}'
}

################################################################################

trap cleanup EXIT
chmod 1777 "${tmpdir}"
export TMPDIR="${tmpdir}"
export LC_ALL=C

while getopts ":hR:" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        R) readonly ros_distro="${OPTARG}" ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((OPTIND - 1))"

################################################################################

# ros_distro
if [ -n "${ros_distro:-}" ]; then
    info "ros_distro: ${ros_distro}"
elif ros_distro="$(detect_ros_distro)"; then
    readonly ros_distro="${ros_distro}"
    info "detected ros_distro: ${ros_distro}"
else
    die "failed to get and/or detect ros_distro"
fi

################################################################################

info "finding shared objects in /opt/ros/${ros_distro}/lib..."

sofile_list="$(mktemp -t sofile_list.XXXXXX)"
readonly sofile_list="${sofile_list}"
find \
    "/opt/ros/${ros_distro}/lib" \
    -maxdepth 1 \
    -type f \
    -exec sh -c 'objdump -p "$0" 2>/dev/null | grep -Fq SONAME' {} \; \
    -print \
    >"${sofile_list}"
sort -uo "${sofile_list}" "${sofile_list}"
info "found $(wc -l <"${sofile_list}") shared objects in /opt/ros/${ros_distro}/lib"

info "searching for package owners..."

# find the packages that own the shared object files; output is of the form
#
#     pkg1(, pkg2)*: /path/to/libfoo.so
#     pkg3(, pkg4)*: /path/to/libbar.so
#
dpkg_search="$(mktemp -t dpkg_search.XXXXXX)"
readonly dpkg_search="${dpkg_search}"
xargs dpkg-query --search <"${sofile_list}" >"${dpkg_search}"
sort -uo "${dpkg_search}" "${dpkg_search}"

# Normalize the output from 'dpkg-query --search' from an "adjacency list" to
# an "edge list"; output is of the form
#
#     pkg1\t/path/to/libfoo.so
#     pkg2\t/path/to/libfoo.so
#     pkg3\t/path/to/libbar.so
#     pkg4\t/path/to/libbar.so
#
# Tricky bits:
#
# * Output file is a newline-delimited list of tab-separated pairs; the first
#   field is a package name; the second field is a path to a shared object
#   file.
#
# * This scheme works so long as the tab-separation works. Debian policy
#   forbids any whitespace (including tabs) in Debian package names.[1] While
#   not strictly forbidden, Unix and Linux convention heavily discourages
#   whitespace in paths.[2]
#
# * A single path may be claimed by multiple packages; e.g., consider the
#   output of 'dpkg-query --search /usr/bin'
#
# * Tell awk to globally substitute a tab for each '[,:] '. We need this
#   specificity to avoid breaking within a package name that may contain a
#   colon-architecture suffix; e.g.,
#
#       $ dpkg -S /usr/share/doc/libpcre3
#       libpcre3:amd64: /usr/share/doc/libpcre3
#
package_sofile_list="$(mktemp -t package_sofile_list.XXXXXX)"
readonly package_sofile_list="${package_sofile_list}"
awk '{gsub("[,:] ","\t"); for(i=1;i<NF;++i) printf "%s\t%s\n", $i, $NF}' \
    <"${dpkg_search}" >"${package_sofile_list}"
sort -uo "${package_sofile_list}" "${package_sofile_list}"

package_list="$(mktemp -t package_list.XXXXXX)"
readonly package_list="${package_list}"
cut -f1 <"${package_sofile_list}" >"${package_list}"
sort -uo "${package_list}" "${package_list}"

info "found $(wc -l <"${package_list}") package owners"

while read -r package; do
    # Change to a clean directory to prevent dpkg-gensymbols from using
    # `${PWD}/debian/*` to discover the package name and/or version.
    cd "$(mktemp -dt "${package}.XXXXXX")"

    # use the current version of the installed package
    if ! version="$(dpkg-query -Wf'${Version}' "${package}")"; then
        die "FAILURE: dpkg-query -Wf'\${Version}' ${package}"
    fi

    # https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#the-symbols-system
    symbols="/etc/dpkg/symbols/${package}.symbols"
    mkdir -p "$(dirname "${symbols}")"
    rm -f "${symbols}"

    info "${package} ${version} ${symbols}"

    # https://manpages.debian.org/buster/dpkg-dev/dpkg-gensymbols.1.en.html
    #
    # get xargs to do invocations like this:
    #
    #     dpkg-gensymbols \
    #         -p"${package}" \
    #         -v"${version}" \
    #         -O"${symbols}" \
    #         -e/opt/ros/${ros_distro}/lib/libfoo.so \
    #         -e/opt/ros/${ros_distro}/lib/libbar.so \
    #         -e/opt/ros/${ros_distro}/lib/libqux.so
    #
    sed -nr "s|^${package}\t(.+)$|-e\1|gp" <"${package_sofile_list}" \
        | xargs dpkg-gensymbols -q -p"${package}" -v"${version}" -O"${symbols}" >/dev/null

done <"${package_list}"

info "done"

exit "$?"

# References:
#
# [1]:https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-source
# , Section 5 "Control files and their fields", Section 5.6 "List of fields",
# Section 5.6.1 "Source"
#
# > Package names ... must consist only of lower case letters (a-z), digits
# > (0-9), plus (+) and minus (-) signs, and periods (.). They must be at least
# > two characters long and must start with an alphanumeric character.
#
# [2]:https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_282
#
# > 3.282 Portable Filename Character Set
# >
# > The set of characters from which portable filenames are constructed.
# >
# > A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
# > a b c d e f g h i j k l m n o p q r s t u v w x y z
# > 0 1 2 3 4 5 6 7 8 9 . _ -
#
