#!/bin/sh

# scrippies/setup-dev

set -eu

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly whatami="$(basename "${here}").$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

log() { echo "${whatami}[$$]: $@" >&2; }
error() { log "ERROR: $@"; }
warning() { log "WARNING: $@"; }
info() { log "INFO: $@"; }

die() {
    error "$@"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}"
    return "${status}"
}

usage() {
    cat <<EOF
Usage: $(basename ${this}) [DISTRIBUTION]
Setup a host for development

Notes:

    DISTRIBUTION defaults to \$(lsb_release --short --codename).

Examples:

    \$ $(basename ${this})           # requires lsb_release

    \$ $(basename ${this}) xenial

    \$ $(basename ${this}) bionic
EOF
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

if ! [ 0 -eq "$(id -u)" ]; then
    sudo "${this}"
    exit "$?"
fi

info "configuring apt"
"${here}/configure-apt" $@

info "configuring rosdistro"
"${here}/configure-rosdistro"

info "updating apt"
apt-get update -y

info "installing packages"
# TODO: USE ROSDEP INSTEAD
apt-get install -y --no-install-recommends \
    build-essential \
    freeglut3 \
    freeglut3-dev \
    gdebi \
    libglfw3-dev \
    libglu1-mesa-dev \
    libgtk-3-dev \
    libpcl-dev \
    libpng12-dev \
    librealsense2-dbg=2.16.0-0~realsense0.85 \
    librealsense2-dev=2.16.0-0~realsense0.85 \
    librealsense2-dkms=1.3.1-0ubuntu3 \
    librealsense2=2.16.0-0~realsense0.85 \
    librscalibrationapi=2.6.4.0 \
    librscalibrationtool=2.6.4.0 \
    libusb-1.0-0-dev \
    libusb-dev \
    mesa-common-dev \
    mesa-utils \
    pcl-tools \
    python-wstool \
    ros-kinetic-controller-manager \
    ros-kinetic-cv-bridge \
    ros-kinetic-desktop-full \
    ros-kinetic-hardware-interface \
    ros-kinetic-image-geometry \
    ros-kinetic-image-transport \
    ros-kinetic-moveit \
    ros-kinetic-pcl-ros \
    ros-kinetic-realtime-tools \
    ros-kinetic-resource-retriever \
    ros-kinetic-trac-ik \
    && true
