#!/bin/sh

# scrippies/tar-deterministic

set -eu

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly whatami="$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

log() { echo "${whatami}[$$]: $@" >&2; }
error() { log "ERROR: $@"; }
warning() { log "WARNING: $@"; }
info() { log "INFO: $@"; }

die() {
    error "$@"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}"
    return "${status}"
}

usage() {
    cat <<EOF
Usage: $(basename ${this}) [OPTION]...
Create a deterministic tarball from the contents of working directory.

Options:
    -h            print this usage and return success
    -C WORKDIR    run as if started in WORKDIR (default: \$PWD)
    -o OUTFILE    write to OUTFILE (default: \$WORKDIR.tar)
    -m MTIME      override mtime (default: "now")

Examples:

    \$ $(basename ${this})

    \$ $(basename ${this}) -C \$PWD

    \$ $(basename ${this}) -C \$PWD -o \$PWD.tar

Notes:

    * MTIME must be something \`date -d\` understands.

References:

    * https://reproducible-builds.org/docs/archives

EOF
}

vet_workdir() {
    local result=""
    if ! result="$(readlink -f "$1")"; then
        error "bad path: $1"
        return 1
    fi
    if ! [ -d "${result}" ]; then
        error "missing directory: ${result}"
        return 1
    fi
    echo "${result}"
    return 0
}

vet_outfile() {
    local result=""
    if ! result="$(readlink -f "$1")"; then
        error "bad path: $1"
        return 1
    fi
    if [ -f "${result}" ]; then
        if ! [ "true" = "${requested_force:-false}" ]; then
            error "exists: ${result}"
            return 1
        fi
        warning "extant file: ${result}"
        warning "$(rm -v "${result}")"
    fi
    echo "${result}"
    return 0
}

vet_mtime() {
    local result=""
    if ! result="@$(date -d "$1" +%s)"; then
        error "bad mtime: $1"
        return 1
    fi
    echo "${result}"
    return 0
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

while getopts ":hfC:o:m:" opt; do
    case "${opt}" in
        h)
            usage
            exit "$?"
            ;;
        f) requested_force="true" ;;
        C) workdir="${OPTARG}" ;;
        o) outfile="${OPTARG}" ;;
        m) mtime="${OPTARG}" ;;
        :) die "Missing argument: -${OPTARG}" ;;
        \?) die "Invalid option: -${OPTARG}" ;;
    esac
done
shift "$((${OPTIND} - 1))"

# workdir
if ! [ -n "${workdir:-}" ]; then
    workdir="${PWD}"
    warning "defaulted workdir: ${workdir}"
fi
if ! workdir="$(vet_workdir "${workdir}")"; then
    die "FAILURE: vet_workdir ${workdir}"
fi
info "workdir: ${workdir}"

# outfile
if ! [ -n "${outfile:-}" ]; then
    outfile="${workdir}.tar"
    warning "defaulted outfile: ${outfile}"
fi
if ! outfile="$(vet_outfile "${outfile}")"; then
    die "FAILURE: vet_outfile ${outfile}"
fi
info "outfile: ${outfile}"

# mtime
if ! [ -n "${mtime:-}" ]; then
    mtime="now"
    warning "defaulted mtime: ${mtime}"
fi
if ! mtime="$(vet_mtime "${mtime}")"; then
    die "FAILURE: vet_mtime ${mtime}"
fi
info "mtime: ${mtime} ($(date -uIs -d "${mtime}"))"

# ###############################################
# Explanation for a horrible little shell snippet
# ###############################################
#
# `sed 's/./\\&/g'`
#
# This is some shell trickery to deal with whitespace-containing filenames. The
# original belongs to Rich Felker, and it was good enough for me to steal when
# Makeself needed such a patch.
#
# * http://www.etalabs.net/sh_tricks.html
# * https://github.com/megastep/makeself/pull/153
#
#
# `--pax-option "exthdr.name=%d/PaxHeaders.0/%f"`
#
# If tar tries to write a pax header, then this option should keep the PID
# (which is not deterministic) out of the archive. The golang folks do this, so
# it seems like a generally good idea for any tar implementation, not just GNU.
#
# * https://groups.google.com/forum/#!msg/golang-dev/8mY37Lc-AsQ/xC2oVQ2iEwAJ
# * https://github.com/golang/go/issues/12358
#
#
# `--pax-option="delete=atime"`
# `--pax-option="delete=ctime"`
# `--pax-option="delete=mtime"`
# `--mtime=0`
#
# This is some sillyness to force both GNU tar v1.28 (xenial) and v1.29
# (bionic) to deterministically create identical archives; i.e., any two with
# identical content will have identical checksums. This turns out to be Really
# Difficult.
#
# Here, with the `--pax-option=delete=atime,delete=ctime,delete=mtime` options,
# I'm asking `tar` to keep timestamps out of the archive. For reasons that
# escape me, this is necessary to stop GNU tar v1.29 from writing the Pax
# Header. Conversely, GNU tar v1.28 seems happy to omit the Pax Header under
# all the conditions I tested.
#
# Note that I'm _also_ specifying `--mtime` which causes the given Unix
# Timestamp to be written into the archive as the modification time for all
# members. A sane person would expect `--mtime=...` and
# `--pax-option="delete=mtime"` to mutually conflict, so that should inform
# your opinion of the GNU tar developers.
#
# * https://www.gnu.org/software/tar/manual/tar.html#SEC147
(
    cd "${workdir}"
    find . ! -type d \
        | sort \
        | sed 's/./\\&/g' \
        | xargs tar \
            --numeric-owner \
            --owner=0 \
            --group=0 \
            --format=pax \
            --pax-option="exthdr.name=%d/PaxHeaders.0/%f" \
            --pax-option="delete=atime" \
            --pax-option="delete=ctime" \
            --pax-option="delete=mtime" \
            --mtime="${mtime}" \
            -rf "${outfile}"
)
