#!/bin/sh

# scrippies/install-librscalibrationapi

set -euvx

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly whatami="$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

log() { echo "${whatami}[$$]: $@" >&2; }
error() { log "ERROR: $@"; }
warning() { log "WARNING: $@"; }
info() { log "INFO: $@"; }

die() {
    error "$@"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}" || true
    return "${status}"
}

usage() {
    cat <<EOF
Usage: $0 [OPTION]... LIBRSCALIBRATIONAPI_DEB_FILE
Tweak the given librscalibrationapi Debian archive.

Options
    -h            print this usage and return success

Examples:

    \$ $0 -h

    \$ $0 ./librscalibrationapi_2.6.8.0_amd64.deb

EOF
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

while getopts ":hC:u:" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((${OPTIND} - 1))"

if ! [ 1 -eq "$#" ]; then
    die "bad args"
fi

if ! deb_file="$(readlink -f "$1")"; then
    die "missing path: $1"
fi
if ! [ -f "${deb_file}" ]; then
    die "missing file: ${deb_file}"
fi

# extract, remove references to libpng*, delete executables, delete examples,
# delete empty directories, and rebuild
deb_dir="${deb_file%.deb}"
dpkg-deb --raw-extract "${deb_file}" "${deb_dir}"
sed -ri '/^Depends: /s/libpng[^,]+[, ]*//g' "${deb_dir}/DEBIAN/control"
find "${deb_dir}" -type f -perm /111 -exec rm -vf {} \;
find "${deb_dir}" -type d -name 'examples' | xargs -r rm -vrf
find "${deb_dir}" -type d -empty -delete
dpkg-deb --build "${deb_dir}" "${deb_file}"

exit "$?"
