#!/bin/sh

# scrippies/wrap-colcon

set -euvx

this="$(readlink -f "$0")"
readonly this="${this}"
whatami="$(basename "${this}")"
readonly whatami="${whatami}"
tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"
readonly tmpdir="${tmpdir}"

log() { echo "${whatami}[$$]: $*" >&2; }
error() { log "ERROR: $*"; }
warning() { log "WARNING: $*"; }
info() { log "INFO: $*"; }

die() {
    error "$*"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}"
    return "${status}"
}

usage() {
    cat <<EOF

Usage: $0 COLCON_VERB [[--] [COLCON_ARG]... [COLCON_OPT]...]
Wrap an invocation to colcon with some helpful options.

Examples:

    \$ $0

    \$ $0 build

    \$ $0 test --packages-select-by-dep rtr_utils

    \$ $0 test-result

EOF
}

# Run the given command in a subshell piped to sed because (1.) we can protect
# the terminal from the given command and (2.) we can nuke all of the ANSI
# escape codes. Because the subshell can't modifiy variables in its parent, we
# have to write the colcon exit status into a temporary file and read it after
# exiting the subshell.
# 
# References:
#
# * https://en.wikipedia.org/wiki/ANSI_escape_code
# * https://unix.stackexchange.com/a/14699
# * https://unix.stackexchange.com/a/55547
deansi_eval() {
    # shellcheck disable=SC2039
    local return_code=""
    return_code="$(mktemp -t return_code.XXXXXX)"
    if eval "$@"; then
        echo "$?" >"${return_code}"
    else
        echo "$?" >"${return_code}"
    fi | sed 's/\x1b\[[0-9;?]*[JKmsu]//g'
    return "$(
        xargs <"${return_code}"
        rm -f "${return_code}"
    )"
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C
export COLCON_DEFAULT_EXECUTOR=parallel
export COLCON_EXTENSION_BLOCKLIST=colcon_core.event_handler.desktop_notification

while getopts ":h" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((OPTIND - 1))"

if ! [ 0 -lt "$#" ]; then
    die "bad args"
fi

readonly verb="$1"
shift

# options unique to the given verb
case "${verb}" in
    build)
        set -- \
            --cmake-args \
            " -DCMAKE_CPP_FLAGS=${CPPFLAGS:-}" \
            " -DCMAKE_CXX_COMPILER=${CXX:-$(command -v c++)}" \
            " -DCMAKE_CXX_FLAGS=${CXXFLAGS:-}" \
            " -DCMAKE_C_COMPILER=${CC:-$(command -v cc)}" \
            " -DCMAKE_C_FLAGS=${CFLAGS:-}" \
            " -DCMAKE_VERBOSE_MAKEFILE=true" \
            "$@"
        ;;
    test)
        set -- \
            --abort-on-error \
            --return-code-on-test-failure \
            "$@"
        ;;
    *) ;;
esac

# parallel workers and event handlers
case "${verb}" in
    build | test)
        set -- \
            --parallel-workers "$(((1 + $(nproc)) / 2))" \
            --event-handlers \
            compile_commands+ \
            console_cohesion+ \
            console_direct+ \
            console_package_list+ \
            console_start_end+ \
            console_stderr+ \
            event_log+ \
            log+ \
            log_command+ \
            status+ \
            store_result+ \
            summary+ \
            terminal_title- \
            "$@"
        ;;
    *) ;;
esac

# verbosity
case "${verb}" in
    extension-points | extensions | test-result)
        set -- --verbose --all "$@"
        ;;
    *) ;;
esac

deansi_eval colcon "${verb}" "$@"

exit "$?"
