#!/bin/sh

# scrippies/wrap-catkin

set -euvx

readonly this="$(readlink -f "$0")"
readonly here="$(dirname "${this}")"
readonly whatami="$(basename "${this}")"
readonly tmpdir="$(mktemp -dt "${whatami}.XXXXXX")"

log() { echo "${whatami}[$$]: $*" >&2; }
error() { log "ERROR: $*"; }
warning() { log "WARNING: $*"; }
info() { log "INFO: $*"; }

die() {
    error "$*"
    usage >&2
    exit 1
}

cleanup() {
    status="$?"
    rm -rf "${tmpdir}"
    return "${status}"
}

usage() {
    cat <<EOF
Usage: $0 -- [CATKIN_ARG]... [CATKIN_OPT]...
Wrap an invocation to catkin with some super-verbose options.

Examples:

    \$ $0

    \$ $0 build rtr_toolkit

    \$ $0 run_tests rtr_math --no-deps

Caveats:

    * assumes GNU make

EOF
}

################################################################################

trap cleanup EXIT
export TMPDIR="${tmpdir}"
export LC_ALL=C

while getopts ":h" opt; do
    case "${opt}" in
        h)
            usage
            exit 0
            ;;
        :) die "missing argument: -${OPTARG}" ;;
        \?) die "bad option: -${OPTARG}" ;;
    esac
done
shift "$((OPTIND - 1))"

catkin "$@" \
    --no-color \
    --no-notify \
    --no-status \
    --summarize \
    --verbose \
    --cmake-args \
    -DCMAKE_CPP_FLAGS="${CPPFLAGS:-}" \
    -DCMAKE_CXX_COMPILER="${CXX:-$(command -v c++)}" \
    -DCMAKE_CXX_FLAGS="${CXXFLAGS:-}" \
    -DCMAKE_C_COMPILER="${CC:-$(command -v cc)}" \
    -DCMAKE_C_FLAGS="${CFLAGS:-}" \
    -DCMAKE_VERBOSE_MAKEFILE=true \
    -- \
    --make-args \
    "${MAKEFLAGS:- --jobs=$((1 + $(nproc) >> 1)) --load-average=$(nproc)}" \
    --

exit "$?"
